### ISSUE TITLE
Problems Upgrading to RequireJS 2.0

### ISSUE THREAD

**Issue by neiesc** [neiesc/dochub#4]
Change to work on version 2.1.x
[Upgrading to RequireJS 2.0](https://github.com/jrburke/requirejs/wiki/Upgrading-to-RequireJS-2.0)

**Comment by serv-inc** [comment]
Error message with node v0.12.7:

```
/dochub/node_modules/requirejs/bin/r.js:2267
    if (path.existsSync(url)) {
             ^
TypeError: undefined is not a function
at requirejsVars.nodeLoad.req.load (/home/web/Downloads/dochub/node_modules/requirejs/bin/r.js:2267:18)
at resume (/home/web/Downloads/dochub/node_modules/requirejs/bin/r.js:1282:65)
at Object.context.require (/home/web/Downloads/dochub/node_modules/requirejs/bin/r.js:1481:25)
at requirejs (/home/web/Downloads/dochub/node_modules/requirejs/bin/r.js:1684:24)
at Object.<anonymous> (/home/web/Downloads/dochub/scraper/jquery.js:3:1)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
```
